spring:
  application:
    name: geoflow-processor
  datasource:
    url: jdbc:postgresql://localhost:5432/geoflow
    username: geoflow
    password: geoflow123
  kafka:
    bootstrap-servers: localhost:9092
  flyway:
    enabled: true

geoflow:
  timezone: America/Sao_Paulo
  kafka:
    topics:
      job-requested: geoflow.job.requested
      job-completed: geoflow.job.completed
      job-failed: geoflow.job.failed

management:
  endpoints:
    web:
      exposure:
        include: health,info

camel:
  springboot:
    main-run-controller: true
